import com.github.javafaker.Faker;
import com.sun.xml.internal.rngom.parse.host.Base;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.support.ui.Select;

import java.util.Locale;

public class CreacionEncuesta extends BaseTest{
    Locale locale = new Locale("es_MX");
    Faker faker = new Faker(locale);
    @Test
    public void crearEncuestaTest(){
//        InicioSesion is = new InicioSesion();
//        try{
//        is.testInicioSesion();}
//        catch (Exception e){
//            e.getMessage();
//        }
        driver.get("http://qa.walook.com.mx:81/encuesta");
        try {
            //driver.findElement(By.linkText("Inicio")).click();
            driver.findElement(By.linkText("Crear encuesta")).click();
            driver.findElement(By.id("nombre")).click();
            driver.findElement(By.id("nombre")).clear();
            driver.findElement(By.id("nombre")).sendKeys("Nueva encuesta");
            driver.findElement(By.id("btnGuardarEncuesta")).click();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='¡Encuesta guardada correctamente!'])[1]/following::button[1]")).click();
            driver.findElement(By.id("pregunta")).click();
            new Select(driver.findElement(By.id("pregunta"))).selectByVisibleText("Texto");
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::i[1]")).click();
            driver.findElement(By.name("descripcion")).click();
            driver.findElement(By.name("descripcion")).clear();
            driver.findElement(By.name("descripcion")).sendKeys("Cual es su nombre?");
            driver.findElement(By.id("btn_guardar_formulario_modalTexto")).click();
            driver.findElement(By.id("pregunta")).click();
            new Select(driver.findElement(By.id("pregunta"))).selectByVisibleText("Checkbox");
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::i[1]")).click();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='¿obligatoria?'])[5]/following::input[1]")).click();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='¿obligatoria?'])[5]/following::input[1]")).clear();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='¿obligatoria?'])[5]/following::input[1]")).sendKeys("Que le gusto de nuestro negocio?");
            driver.findElement(By.id("input_check_respuesta")).clear();
            driver.findElement(By.id("input_check_respuesta")).sendKeys("Atención al cliente");
            driver.findElement(By.id("input_check_valor")).clear();
            driver.findElement(By.id("input_check_valor")).sendKeys("25");
            driver.findElement(By.id("btn_agregar_respuesta_checkbox")).click();
            driver.findElement(By.id("input_check_respuesta")).click();
            driver.findElement(By.id("input_check_respuesta")).clear();
            driver.findElement(By.id("input_check_respuesta")).sendKeys("Comida");
            driver.findElement(By.id("input_check_valor")).click();
            driver.findElement(By.id("input_check_valor")).clear();
            driver.findElement(By.id("input_check_valor")).sendKeys("25");
            driver.findElement(By.id("btn_agregar_respuesta_checkbox")).click();
            driver.findElement(By.id("input_check_respuesta")).click();
            driver.findElement(By.id("input_check_respuesta")).clear();
            driver.findElement(By.id("input_check_respuesta")).sendKeys("Ambiente");
            driver.findElement(By.id("input_check_valor")).click();
            driver.findElement(By.id("input_check_valor")).clear();
            driver.findElement(By.id("input_check_valor")).sendKeys("25");
            driver.findElement(By.id("btn_agregar_respuesta_checkbox")).click();
            driver.findElement(By.id("input_check_respuesta")).click();
            driver.findElement(By.id("input_check_respuesta")).clear();
            driver.findElement(By.id("input_check_respuesta")).sendKeys("Variedad de alimentos");
            driver.findElement(By.id("input_check_valor")).click();
            driver.findElement(By.id("input_check_valor")).clear();
            driver.findElement(By.id("input_check_valor")).sendKeys("25");
            driver.findElement(By.id("btn_agregar_respuesta_checkbox")).click();
            driver.findElement(By.id("btn_guardar_formulario_modalCheckbox")).click();
            driver.findElement(By.id("pregunta")).click();
            new Select(driver.findElement(By.id("pregunta"))).selectByVisibleText("Estrella");
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::i[1]")).click();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='¿obligatoria?'])[7]/following::input[1]")).click();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='¿obligatoria?'])[7]/following::input[1]")).clear();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='¿obligatoria?'])[7]/following::input[1]")).sendKeys("En la siguiente escala como califica nuestro servicio?");
            driver.findElement(By.id("input_respuesta_estrella")).clear();
            driver.findElement(By.id("input_respuesta_estrella")).sendKeys("Servicio");
            driver.findElement(By.id("config_escala")).clear();
            driver.findElement(By.id("config_escala")).sendKeys("5");
            driver.findElement(By.id("config_valor")).clear();
            driver.findElement(By.id("config_valor")).sendKeys("100");
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='anidar'])[1]/following::div[4]")).click();
            driver.findElement(By.id("btn_agregar_respuesta_estrella")).click();
            driver.findElement(By.id("btn_guardar_formulario_modalEstrella")).click();
            driver.findElement(By.id("pregunta")).click();
            new Select(driver.findElement(By.id("pregunta"))).selectByVisibleText("Radio Button");
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::i[1]")).click();
            driver.findElement(By.id("descpregunta")).click();
            driver.findElement(By.id("descpregunta")).clear();
            driver.findElement(By.id("descpregunta")).sendKeys("Nos recomendaria?");
            driver.findElement(By.id("input_radio_respuesta")).clear();
            driver.findElement(By.id("input_radio_respuesta")).sendKeys("Si");
            driver.findElement(By.id("input_radio_valor")).clear();
            driver.findElement(By.id("input_radio_valor")).sendKeys("100");
            driver.findElement(By.id("btn_agregar_respuesta_radio")).click();
            driver.findElement(By.id("input_radio_respuesta")).click();
            driver.findElement(By.id("input_radio_respuesta")).clear();
            driver.findElement(By.id("input_radio_respuesta")).sendKeys("No");
            driver.findElement(By.id("input_radio_valor")).clear();
            driver.findElement(By.id("input_radio_valor")).sendKeys("0");
            driver.findElement(By.id("btn_agregar_respuesta_radio")).click();
            driver.findElement(By.id("btn_guardar_formulario_modalRadio")).click();
            driver.findElement(By.id("pregunta")).click();
            new Select(driver.findElement(By.id("pregunta"))).selectByVisibleText("Selección");
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::i[1]")).click();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='¿obligatoria?'])[3]/following::input[1]")).click();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='¿obligatoria?'])[3]/following::input[1]")).clear();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='¿obligatoria?'])[3]/following::input[1]")).sendKeys("Sucursal que visito?");
            driver.findElement(By.id("input_sel_respuesta")).click();
            driver.findElement(By.id("input_sel_respuesta")).clear();
            driver.findElement(By.id("input_sel_respuesta")).sendKeys("Oriente");
            driver.findElement(By.id("input_sel_valor")).clear();
            driver.findElement(By.id("input_sel_valor")).sendKeys("25");
            driver.findElement(By.id("btn_agregar_respuesta_selector")).click();
            driver.findElement(By.id("input_sel_respuesta")).click();
            driver.findElement(By.id("input_sel_respuesta")).clear();
            driver.findElement(By.id("input_sel_respuesta")).sendKeys("Norte");
            driver.findElement(By.id("input_sel_valor")).click();
            driver.findElement(By.id("input_sel_valor")).clear();
            driver.findElement(By.id("input_sel_valor")).sendKeys("25");
            driver.findElement(By.id("btn_agregar_respuesta_selector")).click();
            driver.findElement(By.id("input_sel_respuesta")).click();
            driver.findElement(By.id("input_sel_respuesta")).clear();
            driver.findElement(By.id("input_sel_respuesta")).sendKeys("Poniente");
            driver.findElement(By.id("input_sel_valor")).click();
            driver.findElement(By.id("input_sel_valor")).clear();
            driver.findElement(By.id("input_sel_valor")).sendKeys("25");
            driver.findElement(By.id("btn_agregar_respuesta_selector")).click();
            driver.findElement(By.id("input_sel_respuesta")).click();
            driver.findElement(By.id("input_sel_respuesta")).clear();
            driver.findElement(By.id("input_sel_respuesta")).sendKeys("Sur");
            driver.findElement(By.id("input_sel_valor")).click();
            driver.findElement(By.id("input_sel_valor")).clear();
            driver.findElement(By.id("input_sel_valor")).sendKeys("25");
            driver.findElement(By.id("btn_agregar_respuesta_selector")).click();
            driver.findElement(By.id("btn_guardar_formulario_modalSelector")).click();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::label[1]")).click();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Cual es su nombre?'])[2]/following::input[1]")).click();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Cual es su nombre?'])[2]/following::input[1]")).clear();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Cual es su nombre?'])[2]/following::input[1]")).sendKeys("20");
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Que le gusto de nuestro negocio?'])[2]/following::input[1]")).clear();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Que le gusto de nuestro negocio?'])[2]/following::input[1]")).sendKeys("20");
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='En la siguiente escala como califica nuestro servicio?'])[2]/following::input[1]")).click();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='En la siguiente escala como califica nuestro servicio?'])[2]/following::input[1]")).clear();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='En la siguiente escala como califica nuestro servicio?'])[2]/following::input[1]")).sendKeys("20");
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Nos recomendaria?'])[2]/following::input[1]")).clear();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Nos recomendaria?'])[2]/following::input[1]")).sendKeys("20");
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Sucursal que visito?'])[2]/following::input[1]")).clear();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Sucursal que visito?'])[2]/following::input[1]")).sendKeys("20");
            driver.findElement(By.id("guardarPadre")).click();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Las calificaciones se han guardada con sastifacción'])[1]/following::button[1]")).click();
            driver.findElement(By.id("btnGuardarEncuesta")).click();
            driver.findElement(By.id("nombre")).click();
            driver.findElement(By.id("nombre")).clear();
            driver.findElement(By.id("nombre")).sendKeys("Nueva encuesta10");
            driver.findElement(By.id("btnGuardarEncuesta")).click();
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Agregar encuesta predeterminada'])[1]/following::i[1]")).click();
            driver.findElement(By.id("estado")).click();
            new Select(driver.findElement(By.id("estado"))).selectByVisibleText("Activo");
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Agregar encuesta predeterminada'])[1]/following::i[1]")).click();
            driver.findElement(By.id("estado")).click();
            new Select(driver.findElement(By.id("estado"))).selectByVisibleText("Inactivo");
            driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Agregar encuesta predeterminada'])[1]/following::i[1]")).click();
        } catch (Exception e) {
            Assertions.fail(e.getMessage());
        }
    }
}
